### PR TITLE
#324 fix config server ssh key and bitbucket ssh key

### LINKED ISSUE #324: Error create bitbucket secret

### PR DESCRIPTION
**Pull request by chriskieser**
resolves #324

### CODE REVIEW

File: src/gluon/services/openshift/OCService.ts [hunk 1]
```diff
@@ -231,27 +231,28 @@ export class OCService {
...
-
-        return await OCCommon.commonCommand("secrets new-sshauth",
+        return await OCCommon.commonCommand("create secret generic",
             secretName,
             [],
             [
-                new SimpleOption("-ssh-privatekey", rawSSHKey),
-                new SimpleOption("-ca-cert", QMConfig.subatomic.bitbucket.caPath),
+                new SimpleOption("-from-file=ssh-privatekey", QMConfig.subatomic.bitbucket.cicdPrivateKeyPath),
+                new SimpleOption("-from-file=ca.crt", QMConfig.subatomic.bitbucket.caPath),
```
Comment (kbristow) [inline src/gluon/services/openshift/OCService.ts]: Why are you using the -from-file and create secret generic for this? Does it work better than the new-sshauth secret?

Comment (chriskieser) [reply src/gluon/services/openshift/OCService.ts]: deprcated
`Command "new-sshauth" is deprecated, use oc create secret`

Comment (kbristow) [reply src/gluon/services/openshift/OCService.ts]: Ah I see. Cool cool.
