### PR TITLE
Reference faq

### LINKED ISSUE #361: Consider linking documentation on errors
Once we have an FAQ section in the documentation, we should perhaps provide a link to this page when a command fails so that users can try see if they have a known issue and solution.

### PR DESCRIPTION
**Pull request by KieranHons**
Functionality which allows the user to click on a FAQ hyperlink to the docs

Closes #361

### CODE REVIEW

File: src/gluon/util/shared/Error.ts [hunk 1]
```diff
@@ -20,7 +16,7 @@ export async function handleQMError(messageClient: QMMessageClient, error) {
 
     if (error && "code" in error && error.code === "ECONNREFUSED") {
         logger.error(`Error code suggests and external service is down.\nError: ${util.inspect(error)}`);
-        return await messageClient.send(`❗Unexpected failure. An external service dependency appears to be down.`);
+        return await messageClient.send(`❗Unexpected failure. An external service dependency appears to be down ${url(`${QMConfig.subatomic.docs.baseUrl}/FAQ`, "FAQ")}`);
```
Comment (kbristow) [inline src/gluon/util/shared/Error.ts]: Probably don't put the link on the errors we are not able to deal with. So just add it to the QM error stuff.

File: src/gluon/util/shared/Error.ts [hunk 2]
```diff
@@ -38,7 +35,8 @@ export async function handleQMError(messageClient: QMMessageClient, error) {
         Command: ${error.command}
         Error: ${error.error}`);
 
-        return await messageClient.send(`❗An Openshift command failed to run successfully. Please alert your system admin to check the logs and correct the issue accordingly.`);
+        return await messageClient.send(`❗An Openshift command failed to run successfully. Please alert your system admin to check the logs and correct the issue accordingly ${url(`${QMConfig.subatomic.docs.baseUrl}/FAQ`,
```
Comment (kbristow) [inline src/gluon/util/shared/Error.ts]: Remove here too.

File: src/gluon/util/shared/Error.ts [hunk 3]
```diff
@@ -29,7 +25,8 @@ export async function handleQMError(messageClient: QMMessageClient, error) {
         return await messageClient.send(error.getSlackMessage());
     } else if (error instanceof Error) {
         logger.error(`Error is of default Error type.\nError: ${util.inspect(error)}`);
-        return await messageClient.send(`❗Unhandled exception occurred. Please alert your system admin to check the logs and correct the issue accordingly.`);
+        return await messageClient.send(`❗Unhandled exception occurred. Please alert your system admin to check the logs and correct the issue accordingly ${url(`${QMConfig.subatomic.docs.baseUrl}/FAQ`,
```
Comment (kbristow) [inline src/gluon/util/shared/Error.ts]: Remove here too.
